version: 2

jobs:
  Write:
    docker:
      - image: circleci/node:7.10
    steps:
      - run:
          command: npm run write
      - persist_to_workspace:
          root: .
          paths: . 

  Read:
    docker:
      - image: circleci/node:7.10
    steps:
      - attach_workspace:
          at: .
      - run:
          command: npm install
      - run:
          command: npm run read

workflows:
  version: 2
  Build and Test:
    jobs:
      - Write
      - Load-Balance Tests:
          requires:
            - Read
