version: 2

jobs:
  Write:
    docker:
      - image: circleci/node:8.9.4-stretch-browsers
    steps:
      - checkout
      - run:
          name: Environment Changes
          command: |
            # Make a place to core dumps to live.
            sudo mkdir -p workspace
            sudo chmod a+rwx /workspace
      - run:
          command: ls
      - run:
          command: npm run write
      - persist_to_workspace:
          root: workspace
          paths: .

  Read:
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          command: npm install
      - run:
          command: npm run read

workflows:
  version: 2
  Build and Test:
    jobs:
      - Write
      - Read:
          requires:
            - Write
