version: 2

jobs:
  Write 0:
    docker:
      - image: circleci/node:8.9.4-stretch-browsers
    steps:
      - checkout
      - run:
          name: Environment Changes
          command: |
            # Make a place to core dumps to live.
            sudo mkdir -p ./tmp
            sudo chmod a+rwx ./tmp
      - restore_cache:
          keys:
            - test-groups
      - run:
          command: ls ./tmp
      - run:
          command: node write0.js
      - persist_to_workspace:
          root: ./tmp
          paths: .

  Write 1:
    docker:
      - image: circleci/node:8.9.4-stretch-browsers
    steps:
      - checkout
      - run:
          name: Environment Changes
          command: |
            # Make a place to core dumps to live.
            sudo mkdir -p ./tmp
            sudo chmod a+rwx ./tmp
      - restore_cache:
          keys:
            - test-groups
      - run:
          command: ls
      - run:
          command: node write1.js
      - persist_to_workspace:
          root: ./tmp
          paths: .

  Write 2:
    docker:
      - image: circleci/node:8.9.4-stretch-browsers
    steps:
      - checkout
      - run:
          name: Environment Changes
          command: |
            # Make a place to core dumps to live.
            sudo mkdir -p ./tmp
            sudo chmod a+rwx ./tmp
      - restore_cache:
          keys:
            - test-groups
      - run:
          command: ls
      - run:
          command: node write2.js
      - persist_to_workspace:
          root: ./tmp
          paths: .

  Write 3:
    docker:
      - image: circleci/node:8.9.4-stretch-browsers
    steps:
      - checkout
      - run:
          name: Environment Changes
          command: |
            # Make a place to core dumps to live.
            sudo mkdir -p ./tmp
            sudo chmod a+rwx ./tmp
      - restore_cache:
          keys:
            - test-groups
      - run:
          command: ls
      - run:
          command: node write3.js
      - persist_to_workspace:
          root: ./tmp
          paths: .

  Read:
    docker:
      - image: circleci/node:8.9.4-stretch-browsers
    steps:
      - checkout
      - attach_workspace:
          at: ./tmp
      - run:
          name: Environment Changes
          command: |
            # Make a place to core dumps to live.
            sudo mkdir -p ./test-groups
            sudo chmod a+rwx ./test-groups
      - run:
          command: ls
      - run:
          command: npm install
      - run:
          command: npm run read
      - restore_cache:
          key: test-groups
      - save_cache:
          key: test-groups-{{ epoch }}
          paths:
            - ./test-groups
          when: on_success

workflows:
  version: 2
  Build and Test:
    jobs:
      - Write 0
      - Write 1
      - Write 2
      - Write 3
      - Read:
          requires:
            - Write 0
            - Write 1
            - Write 2
            - Write 3
